export const TYPES = {
  SELECT_SUMMONER: "SELECT_SUMMONER",
  DELETE_SUMMONER: "DELETE_SUMMONER",
  SET_CURRENT_RECIPIENT: "SET_CURRENT_RECIPIENT",
  ADD_MSG: "ADD_MSG",
  CREATE_CHAT: "CREATE_CHAT",
  CHANGE_CHAT: "CHANGE_CHAT",
};
