export const TYPES = {
  RESET_CHAT_REDUCER: "RESET_CHAT_REDUCER",
  CHANGE_USER: "CHANGE_USER",
  CLEAN_CHAT: "CLEAN_CHAT",
  SET_ACTIVE_REGION: "SET_ACTIVE_REGION",
  SET_ACTIVE_USER: "SET_ACTIVE_USER",
  SELECT_SUMMONER: "SELECT_SUMMONER",
  DELETE_SUMMONER: "DELETE_SUMMONER",
  SET_CURRENT_RECIPIENT: "SET_CURRENT_RECIPIENT",
  ADD_MSG: "ADD_MSG",
  CREATE_CHAT: "CREATE_CHAT",
  CHANGE_CHAT: "CHANGE_CHAT",
};
